In [2]:

import pandas as pd

df = pd.read_csv("d_agencia.csv")
df

   agencia_id     nome     tipo  comissao_pct
0           1  Booking      OTA          0.15
1           2  Decolar      OTA          0.17
2           3      CVC  Agência          0.12
3           4  FlyTour  Agência          0.10

In [3]:
import pandas as pd

df = pd.read_csv("d_canal.csv")
df

   canal_id      canal_nome canal_grupo
0         1   Direto - Site      Direto
1         2    Direto - App      Direto
2         3   OTA - Booking         OTA
3         4   OTA - Decolar         OTA
4         5     Corporativo        Corp
5         6  Agência Física     Agência

In [4]:
import pandas as pd

df = pd.read_csv("d_data.csv")
df

,data_id,data,ano,mes,nome_mes,trimestre,dia_semana,fim_de_semana_flag,feriado_flag,alta_temporada_flag
0,20240101,2024-01-01,2024,1,Jan,1,1,0,1,1
1,20240102,2024-01-02,2024,1,Jan,1,2,0,0,1
2,20240103,2024-01-03,2024,1,Jan,1,3,0,0,1
3,20240104,2024-01-04,2024,1,Jan,1,4,0,0,1
4,20240105,2024-01-05,2024,1,Jan,1,5,0,0,1
...,...,...,...,...,...,...,...,...,...,...
726,20251227,2025-12-27,2025,12,Dec,4,6,1,0,1
727,20251228,2025-12-28,2025,12,Dec,4,7,1,0,1
728,20251229,2025-12-29,2025,12,Dec,4,1,0,0,1
729,20251230,2025-12-30,2025,12,Dec,4,2,0,0,1
730,20251231,2025-12-31,2025,12,Dec,4,3,0,0,1

In [6]:
df.data.duplicated(keep=False)

0      False
1      False
2      False
3      False
4      False
       ...
726    False
727    False
728    False
729    False
730    False
Name: data, Length: 731, dtype: bool

In [7]:
 df.drop_duplicates()

,data_id,data,ano,mes,nome_mes,trimestre,dia_semana,fim_de_semana_flag,feriado_flag,alta_temporada_flag
0,20240101,2024-01-01,2024,1,Jan,1,1,0,1,1
1,20240102,2024-01-02,2024,1,Jan,1,2,0,0,1
2,20240103,2024-01-03,2024,1,Jan,1,3,0,0,1
3,20240104,2024-01-04,2024,1,Jan,1,4,0,0,1
4,20240105,2024-01-05,2024,1,Jan,1,5,0,0,1
...,...,...,...,...,...,...,...,...,...,...
726,20251227,2025-12-27,2025,12,Dec,4,6,1,0,1
727,20251228,2025-12-28,2025,12,Dec,4,7,1,0,1
728,20251229,2025-12-29,2025,12,Dec,4,1,0,0,1
729,20251230,2025-12-30,2025,12,Dec,4,2,0,0,1
730,20251231,2025-12-31,2025,12,Dec,4,3,0,0,1